const keNev = document.querySelector("#kerNev");
const veNev = document.querySelector("#vezNev");
const emailcim = document.querySelector("#email");
const cegesTelo = document.querySelector("#tel");
const egesz = document.querySelector("#egesz");
const figyAblak = document.querySelector("#megerosites");
const igenGomb = document.querySelector("#igen");
const nemGomb =document.querySelector("#nem");
const bezaro = document.querySelector('#bezaras');